# Generated by Django 3.2.7 on 2021-12-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('paragraph', models.TextField(max_length=2000)),
                ('citation', models.TextField(max_length=2000)),
                ('sources', models.TextField(max_length=2000)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=12, null=True)),
            ],
        ),
    ]
