# Generated by Django 3.2.7 on 2021-12-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0002_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='citation',
            new_name='citation_and_url',
        ),
        migrations.RemoveField(
            model_name='paragraph',
            name='sources',
        ),
    ]
