# Generated by Django 3.2.7 on 2022-01-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0003_auto_20211203_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
