# Generated by Django 3.2.7 on 2023-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('step2', '0007_socialmediarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediarequest',
            name='org_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
