# Generated by Django 3.2.7 on 2024-01-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('ranks', models.IntegerField(blank=True, null=True)),
                ('sentence', models.TextField(max_length=400)),
                ('keyes', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('owner', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=2, null=True)),
                ('sentence', models.TextField(max_length=400)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='website.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('subject_determinant', models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-', max_length=100)),
                ('subject_number', models.CharField(blank=True, max_length=100, null=True)),
                ('object_determinant', models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-', max_length=100)),
                ('object', models.CharField(max_length=100)),
                ('object_number', models.CharField(max_length=100)),
                ('verb', models.CharField(blank=True, max_length=100, null=True)),
                ('adjective', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentence', to='website.usertopic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
            options={
                'verbose_name_plural': 'Sentence grammar',
            },
        ),
        migrations.CreateModel(
            name='SentenceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(max_length=400)),
                ('sentence_type', models.CharField(max_length=100)),
                ('sentence_grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentences')),
            ],
            options={
                'verbose_name_plural': 'Sentence results',
            },
        ),
        migrations.CreateModel(
            name='SentenceRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_rank', models.CharField(max_length=2, null=True)),
                ('sentence_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentenceresults')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('target_product', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry_data', to='website.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.user'),
        ),
    ]
