# Generated by Django 3.2.7 on 2022-02-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrydata',
            old_name='target_industry',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='industrydata',
            old_name='target_product',
            new_name='keywords',
        ),
    ]
