# Generated by Django 3.2.7 on 2024-01-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='automated_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
