# Generated by Django 3.2.7 on 2022-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220214_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('owner', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('rank', models.CharField(max_length=2, null=True)),
                ('sentence', models.TextField(max_length=400)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
