# Generated by Django 3.2.7 on 2022-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('ranks', models.IntegerField(blank=True, null=True)),
                ('sentence', models.TextField(max_length=400)),
                ('keyes', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
