# Generated by Django 3.2.7 on 2023-10-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_mtopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrydata',
            name='target_industry',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='subject',
        ),
        migrations.AddField(
            model_name='industrydata',
            name='created_by',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrydata',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='industrydata',
            name='modified_by',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrydata',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_topic', to='website.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='industrydata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry_data', to='website.category'),
        ),
        migrations.AddField(
            model_name='sentences',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sentence', to='website.usertopic'),
        ),
    ]
