# Generated by Django 3.2.7 on 2023-06-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20230612_1654'),
        ('website', '0007_auto_20230619_1401'),
    ]

    operations = [
    ]
