# Generated by Django 3.2.7 on 2023-07-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20230619_1556'),
        ('website', '0008_merge_0007_auto_20230612_1654_0007_auto_20230619_1401'),
    ]

    operations = [
    ]
