# Generated by Django 3.2.7 on 2023-09-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0009_merge_20230714_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrydata',
            name='created_by',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrydata',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='industrydata',
            name='modified_by',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='industrydata',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
