# Generated by Django 3.2.7 on 2023-10-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0012_usertopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrydata',
            name='target_industry',
        ),
        migrations.AddField(
            model_name='industrydata',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='industry_data', to='website.category'),
        ),
    ]
