# Generated by Django 3.2.7 on 2023-10-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0013_auto_20231002_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentences',
            name='subject',
        ),
        migrations.AddField(
            model_name='sentences',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sentence', to='website.usertopic'),
        ),
    ]
