# Generated by Django 3.2.7 on 2023-10-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0014_auto_20231002_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertopic',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
