# Generated by Django 3.2.7 on 2023-10-06 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0015_auto_20231006_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='categories', to='website.user'),
        ),
        migrations.AlterField(
            model_name='usertopic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_topic', to='website.user'),
        ),
    ]
