# Generated by Django 3.2.7 on 2023-12-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Article Api Users',
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('subject_determinant',
                 models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-',
                                  max_length=100)),
                ('subject', models.CharField(choices=[('Livinglab', 'Livinglab'), ('Innovation', 'Innovation'),
                                                      ('User experience', 'User experience'),
                                                      ('Storytelling', 'Storytelling'),
                                                      ('Consumer Behaviour', 'Consumer Behaviour'),
                                                      ('Behavioral economics', 'Behavioral economics'),
                                                      ('Consumer Insights', 'Consumer Insights'),
                                                      ('Statistics', 'Statistics')], default='Livinglab',
                                             max_length=100)),
                ('subject_number', models.CharField(blank=True, max_length=100, null=True)),
                ('object_determinant',
                 models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-',
                                  max_length=100)),
                ('object', models.CharField(max_length=100)),
                ('object_number', models.CharField(max_length=100)),
                ('verb', models.CharField(blank=True, max_length=100, null=True)),
                ('adjective', models.CharField(blank=True, max_length=100, null=True)),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article_api.user')),
            ],
            options={
                'verbose_name_plural': 'Sentence grammar',
            },
        ),
        migrations.CreateModel(
            name='IndustryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='', max_length=500, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.CharField(default='', max_length=500, null=True)),
                ('target_industry', models.CharField(max_length=100)),
                ('target_product', models.CharField(max_length=100)),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article_api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
