# Generated by Django 3.2.7 on 2023-12-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('article_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(max_length=400)),
                ('sentence_type', models.CharField(max_length=100)),
                ('sentence_grammar',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_api.sentences')),
            ],
            options={
                'verbose_name_plural': 'Sentence results',
            },
        ),
    ]
