# Generated by Django 3.2.7 on 2023-12-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('article_api', '0002_sentenceresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentenceresults',
            name='created_by',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentenceresults',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sentenceresults',
            name='modified_by',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentenceresults',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
