# Generated by Django 3.2.7 on 2021-10-09 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_determinant', models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-', max_length=100)),
                ('subject', models.CharField(choices=[('Livinglab', 'Livinglab'), ('Innovation', 'Innovation'), ('User experience', 'User experience'), ('Storytelling', 'Storytelling'), ('Consumer Behaviour', 'Consumer Behaviour'), ('Behavioral economics', 'Behavioral economics'), ('Consumer Insights', 'Consumer Insights'), ('Statistics', 'Statistics')], default='Livinglab', max_length=100)),
                ('subject_number', models.CharField(max_length=100)),
                ('object_determinant', models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-', max_length=100)),
                ('object', models.CharField(max_length=100)),
                ('object_number', models.CharField(max_length=100)),
                ('verb', models.CharField(max_length=100)),
                ('adjective', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
            options={
                'verbose_name_plural': 'Sentence grammar',
            },
        ),
        migrations.CreateModel(
            name='SentenceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(max_length=400)),
                ('sentence_type', models.CharField(max_length=100)),
                ('sentence_grammar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentences')),
            ],
            options={
                'verbose_name_plural': 'Sentence results',
            },
        ),
        migrations.CreateModel(
            name='SentenceRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_rank', models.CharField(max_length=2, null=True)),
                ('sentence_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentenceresults')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_industry', models.CharField(choices=[('Technology & Telecom', 'Technology & Telecom'), ('Food & Beverages', 'Food & Beverages'), ('Travel & Leisure', 'Travel & Leisure'), ('Restaurants & Hotels', 'Restaurants & Hotels'), ('Automotive', 'Automotive'), ('Apparel', 'Apparel'), ('Banking & Insurance', 'Banking & Insurance'), ('Chain stores', 'Chain stores'), ('Alcohol', 'Alcohol'), ('Tobacco', 'Tobacco'), ('Business Services & consultancies', 'Business Services & consultancies'), ('Transportation', 'Transportation'), ('Media', 'Media'), ('Heavy equipments', 'Heavy equipments')], max_length=100)),
                ('target_product', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
    ]
