# Generated by Django 3.2.7 on 2022-02-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220214_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrydata',
            old_name='category',
            new_name='target_industry',
        ),
        migrations.RenameField(
            model_name='industrydata',
            old_name='keywords',
            new_name='target_product',
        ),
    ]
