import Modal from "./Modal";
import * as Dialog from "@radix-ui/react-dialog";
import {Cross2Icon} from "@radix-ui/react-icons";
import {SocialComponentForPost, SocialComponentForSchedule,} from "./SocialComponent";

const dummyData = [
    {
        title:
            "The Livinglab was testing all articles  generated by social media automation.",
        paragraph:
            "The Livinglab was testing all articles generated by social media automation to determine its effectiveness in the industry.  Automation has become a popular tool for businesses to increase their reach and engagement with customers.  Automated social media posts allow businesses to quickly and easily post content to multiple platforms, while also providing analytics to measure the impact of those posts.  \n\nThe Livinglab tested the impact of automated posts on engagement, reach, and conversions.  Results showed that automated posts were more effective in terms of reach and engagement than manually crafted posts.  Automated posts also increased conversions, indicating that automation is an effective tool for businesses to increase their reach and engagement with customers.  #test #Bogotá #Bradford #Brisbane",
        Date: "2023-10-09 00:00:00",
        image:
            "http://dowellfileuploader.uxlivinglab.online/camera_component_images/pexels-photo-267371.jpeg",
        source: null,
        PK: "6523f20aa450e4f7a32018e3",
        time: "2023-10-09 12:28:57.485072+00:00",
    },
    {
        title: "Workflow ai digital documentation was tested by the Livinglab.",
        paragraph:
            "Livinglab recently tested Workflow ai digital documentation, a powerful tool that is revolutionizing the industry.  It automates processes and simplifies the way businesses document their operations, saving time and money.  It also provides a secure platform for storing and sharing information, ensuring that data is kept safe and secure.  The Livinglab found Workflow ai to be an invaluable tool for streamlining operations and improving efficiency.  #test #Bogotá #Bradford #Brisbane",
        Date: "2023-10-09 00:00:00",
        image:
            "http://dowellfileuploader.uxlivinglab.online/camera_component_images/pexels-photo-18069161.png",
        source: null,
        PK: "6523e94bdc7f5adf7fbf5c3b",
        time: "2023-10-09 11:51:38.133819+00:00",
    },
    {
        title:
            "Social media automation efficient article generation was tested by the Livinglab.",
        paragraph: "",
        Date: "2023-08-28 00:00:00",
        image:
            "https://images.pexels.com/photos/5678243/pexels-photo-5678243.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64ec57993033b00f16a48c37",
        time: "2023-08-28 08:15:21.627129+00:00",
    },
    {
        title: "Efficient gaming was run by the Storytelling.",
        paragraph: "",
        Date: "2023-08-25 00:00:00",
        image:
            "https://images.pexels.com/photos/1174746/pexels-photo-1174746.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e85a8ef69b24d8de06aa21",
        time: "2023-08-25 07:38:53.195478+00:00",
    },
    {
        title:
            "The Livinglab had optimised it should be working now digital documentation.",
        paragraph: [],
        Date: "2023-08-23 00:00:00",
        image:
            "https://images.pexels.com/photos/3194523/pexels-photo-3194523.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64e5cfe6cf881609a584f6f4",
        time: "2023-08-23 09:22:44.394268+00:00",
    },
    {
        title:
            "The Livinglab was testing Social Media Automation digital documentation.",
        paragraph: [
            "",
            "",
            "The use of social media automation digital documentation in the industry is becoming increasingly popular, and the Livinglab has been testing this technology. This technology offers a number of benefits to businesses, such as improved efficiency, increased customer engagement, and better customer service. Automated social media documentation can help businesses save time and money by automating the process of creating, managing, and distributing content. It can also help businesses better engage with their customers, by providing them with relevant, timely, and engaging content. In addition, automated social media documentation can help businesses track customer interactions and generate valuable insights. Overall, automated social media documentation can help businesses improve their customer service, increase their efficiency, and better engage with their customers.",
        ],
        Date: "2023-08-23 00:00:00",
        image:
            "https://images.pexels.com/photos/7267046/pexels-photo-7267046.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e5ca87d42aeda7dcef84f4",
        time: "2023-08-23 08:59:49.962805+00:00",
    },
    {
        title:
            "Social Media Automation digital documentation was tested by the Livinglab.",
        paragraph: [],
        Date: "2023-08-23 00:00:00",
        image:
            "https://images.pexels.com/photos/5678243/pexels-photo-5678243.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e5c1bc7d5a254f84e0bece",
        time: "2023-08-23 08:22:19.143818+00:00",
    },
    {
        title:
            "The Livinglab was testing Social Media Automation digital documentation.",
        paragraph:
            "The results of the Livinglab's testing showed that Social Media Automation digital documentation is a powerful tool for businesses. It can help them to save time and money while achieving their social media goals. Additionally, it can help them to target specific audiences with their content, ensuring that their messages reach the right people. With this technology, businesses can maximize their social media efforts and get the most out of their campaigns. #socialmediaautomation #aiwriter #welcome",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/205316/pexels-photo-205316.png?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e4e393af1f3f682366a225",
        time: "2023-08-22 16:34:26.897595+00:00",
    },
    {
        title:
            "The Livinglab was testing Social Media Automation digital documentation.",
        paragraph:
            "The results of the Livinglab's testing showed that Social Media Automation digital documentation is a powerful tool for businesses. It can help them to save time and money while achieving their social media goals. Additionally, it can help them to target specific audiences with their content, ensuring that their messages reach the right people. With this technology, businesses can maximize their social media efforts and get the most out of their campaigns.",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/4474036/pexels-photo-4474036.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e4cd2117f621910f3fe162",
        time: "2023-08-22 14:58:41.475935+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph: [],
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/267371/pexels-photo-267371.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e4c811a8b1e2301a2313b8",
        time: "2023-08-22 14:37:03.175640+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph: [
            "",
            "",
            "In recent years, the use of digital documentation has become increasingly popular in the industry. This is due to the fact that digital documentation is more efficient and cost-effective than traditional paper-based systems. However, the use of digital documentation can be difficult to manage and optimize. Fortunately, the Livinglab has developed a workflow AI-driven digital documentation solution that can help businesses and organizations optimize their digital documentation processes.",
            "",
            "The Livinglab's workflow AI-driven digital documentation solution is designed to make digital documentation more efficient and cost-effective. It uses AI-driven technology to analyze and optimize the digital documentation process. This includes identifying inefficiencies in the process, as well as optimizing the workflow to ensure that the most efficient process is being used. Additionally, the AI-driven technology can be used to automate certain aspects of the process, such as data entry and document retrieval.",
            "",
            "The Livinglab's workflow AI-driven digital documentation solution can also be used to ensure that digital documents are secure. The AI-driven technology can be used to detect and prevent unauthorized access to digital documents. Additionally, the AI-driven technology can be used to detect and prevent data breaches. This helps to ensure that digital documents are secure and confidential.",
            "",
            "The Livinglab's workflow AI-driven digital documentation solution can also be used to ensure that digital documents are up-to-date. The AI-driven technology can be used to detect changes in the digital documents and update them accordingly. This helps to ensure that digital documents are always up-to-date and accurate.",
            "",
            "Overall, the Livinglab's workflow AI-driven digital documentation solution can help businesses and organizations optimize their digital documentation processes. The AI-driven technology can help to make digital documentation more efficient and cost-effective. Additionally, the AI-driven technology can be used to ensure that digital documents are secure and up-to-date. The Livinglab's workflow AI-driven digital documentation solution is an effective way to optimize digital documentation processes in the industry.",
        ],
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/6623836/pexels-photo-6623836.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e4c69caf1f3f682366a09d",
        time: "2023-08-22 14:30:50.073608+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph:
            "The Livinglab's optimised digital documentation for workflow AI has been a major step forward in the industry. It has allowed businesses to create more efficient processes and reduce the amount of time spent on manual tasks. This has allowed businesses to increase their productivity and reduce costs. It has also allowed businesses to increase their security and reduce the risk of data breaches.",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/6623836/pexels-photo-6623836.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e492c3af1f3f6823669ed3",
        time: "2023-08-22 10:49:39.089852+00:00",
    },
    {
        title: "The Livinglab was optimising the Efficient testing credits.",
        paragraph:
            "Overall, the Livinglab has been optimising the efficient testing credits in order to help companies to better understand and use them in the most effective way. This has allowed companies to save time and resources when testing their products and services, while also ensuring that they are of the highest quality. As the world of technology continues to evolve, the use of testing credits is becoming increasingly important, and the Livinglab is helping to ensure that they are used in the most efficient way possible.",
        Date: "2023-08-21 00:00:00",
        image:
            "https://images.pexels.com/photos/4031654/pexels-photo-4031654.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e369acfa46c648294c6e44",
        time: "2023-08-21 13:42:04.063116+00:00",
    },
    {
        title: "Workflow ai digital documentation was tested by the Livinglab.",
        paragraph:
            "Overall, the Livinglab found that Workflow ai was an effective and reliable digital documentation platform that could help businesses streamline their processes and improve their productivity. It is an ideal platform for businesses looking to become more efficient and effective.",
        Date: "2023-08-21 00:00:00",
        image:
            "https://images.pexels.com/photos/8728291/pexels-photo-8728291.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e32182fa46c648294c68a0",
        time: "2023-08-21 08:34:09.034304+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph:
            "Overall, the Livinglab’s testing of the automated content generation system was successful and showed that it could be a useful tool for businesses looking to streamline their social media content creation. The system is still in its early stages, but it is clear that it has the potential to revolutionize the way businesses manage their social media accounts.",
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/6953993/pexels-photo-6953993.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64df7f6aea6a62011fe26ebb",
        time: "2023-08-18 14:25:41.716838+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph: "#Dowell #SocialMedia",
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/262508/pexels-photo-262508.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64df3a74ea6a62011fe2689a",
        time: "2023-08-18 09:31:30.961977+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph:
            "Overall, the Livinglab’s testing of the automated content generation system was successful and showed that it could be a useful tool for businesses looking to streamline their social media content creation. The system is still in its early stages, but it is clear that it has the potential to revolutionize the way businesses manage their social media accounts.",
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/2818118/pexels-photo-2818118.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64df39442a0ed60b499b8c84",
        time: "2023-08-18 09:26:26.575453+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph: null,
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/2228555/pexels-photo-2228555.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64df38d9ea6a62011fe26863",
        time: "2023-08-18 09:24:39.123587+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph:
            "Overall, the Livinglab's testing has shown that social media automation and article generation are highly effective tools for businesses looking to stay ahead of the competition. Automation can save businesses time and money, while also ensuring that their content is optimized for search engine visibility. Businesses should consider utilizing this technology to ensure that their content is up-to-date and engaging.",
        Date: "2023-08-17 00:00:00",
        image:
            "https://images.pexels.com/photos/4098560/pexels-photo-4098560.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64dddc4de698531bfea79d03",
        time: "2023-08-17 08:37:33.645693+00:00",
    },
    {
        title: "An Efficient testing was Workinged by the Livinglab.",
        paragraph:
            "The Maine Coon is the largest, with males reaching an average of 3.5 feet long. The smallest breed is the Singapura, native to Singapore, with adult females weighing as little as four pounds. One of the most unusual-looking cats is the Sphynx, a mostly hairless cat known for being robust and intelligent.",
        Date: "2023-08-16 00:00:00",
        image:
            "https://images.pexels.com/photos/8154655/pexels-photo-8154655.jpeg?auto=compress&cs=tinysrgb&h=350",
        source:
            "https://www.nationalgeographic.com/animals/mammals/facts/domestic-cat",
        PK: "64dcbaecb4bf95c9758f36e1",
        time: "2023-08-16 12:02:48.103927+00:00",
    },
    {
        title:
            "Social Media Automation digital documentation was tested by the Livinglab.",
        paragraph: null,
        Date: "2023-08-10 00:00:00",
        image:
            "https://images.pexels.com/photos/6954220/pexels-photo-6954220.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64d4ba70be7f305101fc18ea",
        time: "2023-08-10 10:22:40.473270+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph:
            "Overall, the optimisation of workflow ai digital documentation by the Livinglab has revolutionised the way businesses manage their documents and information. This technology has enabled businesses to streamline their document management processes, improve their customer service, and increase their data security. As a result, businesses can now operate more efficiently and securely.",
        Date: "2023-07-11 00:00:00",
        image:
            "https://images.pexels.com/photos/5553674/pexels-photo-5553674.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64ad8aa77710b43f9f6f3c09",
        time: "2023-07-11 17:00:22.831704+00:00",
    },
    {
        title:
            "A digital documentation was workflowed optimisation by the Livinglab.",
        paragraph:
            "The Livinglab has developed a digital documentation workflow that is suitable for use in a range of construction projects. This workflow has been designed to improve the efficiency of construction projects by reducing the amount of time spent on documentation and improving the accuracy of construction drawings.",
        Date: "2023-05-31 00:00:00",
        image:
            "https://images.pexels.com/photos/6457481/pexels-photo-6457481.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "6477030e5ebadafe05d5b1fd",
        time: "2023-05-31 08:19:23.241010+00:00",
    },
    {
        title:
            "The Livinglab has informed workflow ai will recommend efficient processes for your task.",
        paragraph:
            "The Livinglab has informed workflow ai will recommend efficient processes for your task. that discusses using in the industry. Workflow ai is a branch of artificial intelligence that is concerned with the automation of workflows and processes. It is said to be able to improve the efficiency of these processes by up to 30%.",
        Date: "2023-05-31 00:00:00",
        image:
            "https://images.pexels.com/photos/8439091/pexels-photo-8439091.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64776ceb868d660a33267f3d",
        time: "2023-05-31 15:51:04.278347+00:00",
    },
    {
        title:
            "Workflow ai digital documentation was tested by the User experience.",
        paragraph: null,
        Date: "2023-08-08 00:00:00",
        image:
            "https://images.pexels.com/photos/5668888/pexels-photo-5668888.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64d209a774c24a57968832a8",
        time: "2023-08-08 09:23:51.220090+00:00",
    },
    {
        title: "Workflow digital documentation was informed by the Livinglab.",
        paragraph: null,
        Date: "2023-08-14 00:00:00",
        image:
            "https://images.pexels.com/photos/4559592/pexels-photo-4559592.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64da1baa38177cbac85e5706",
        time: "2023-08-14 12:18:49.162109+00:00",
    },
    {
        title: "An Efficient testing was Workinged by the Livinglab.",
        paragraph:
            "The Maine Coon is the largest, with males reaching an average of 3.5 feet long. The smallest breed is the Singapura, native to Singapore, with adult females weighing as little as four pounds. One of the most unusual-looking cats is the Sphynx, a mostly hairless cat known for being robust and intelligent.",
        Date: "2023-08-16 00:00:00",
        image:
            "https://images.pexels.com/photos/8154655/pexels-photo-8154655.jpeg?auto=compress&cs=tinysrgb&h=350",
        source:
            "https://www.nationalgeographic.com/animals/mammals/facts/domestic-cat",
        PK: "64dcbb70d89b20e93e44aa39",
        time: "2023-08-16 12:05:02.380913+00:00",
    },
    {
        title: "The small gitft was presented by the Livinglab.",
        paragraph:
            "Overall, the small gift presented by the Livinglab is a great tool for companies to use in the industry. It provides access to a range of digital solutions that can help them to increase their efficiency, reduce costs, and improve their customer service. This makes it an invaluable tool for companies who are looking to stay competitive in today's digital world.",
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/4792679/pexels-photo-4792679.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64df338fce28771063929140",
        time: "2023-08-18 09:02:07.033881+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph: null,
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/4754688/pexels-photo-4754688.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64df390f6079b2d69a81eaae",
        time: "2023-08-18 09:25:33.803176+00:00",
    },
    {
        title:
            "The Livinglab was testing Social media automation efficient article generation.",
        paragraph:
            "Overall, the Livinglab’s testing of the automated content generation system was successful and showed that it could be a useful tool for businesses looking to streamline their social media content creation. The system is still in its early stages, but it is clear that it has the potential to revolutionize the way businesses manage their social media accounts.",
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/2818118/pexels-photo-2818118.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64df39bb950a476cfbc5f205",
        time: "2023-08-18 09:28:26.015548+00:00",
    },
    {
        title: "Livinglab.",
        paragraph: "",
        Date: "2023-08-18 00:00:00",
        image:
            "https://images.pexels.com/photos/6102512/pexels-photo-6102512.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64df49a6b0d12aacfd672af3",
        time: "2023-08-18 10:36:20.231694+00:00",
    },
    {
        title: "The small gitft was presented by the Livinglab.",
        paragraph: null,
        Date: "2023-08-21 00:00:00",
        image:
            "https://images.pexels.com/photos/1775115/pexels-photo-1775115.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: null,
        PK: "64e31823fb4d11845e041db5",
        time: "2023-08-21 07:54:10.210660+00:00",
    },
    {
        title: "Workflow ai digital documentation was tested by the Livinglab.",
        paragraph:
            "The use of digital documentation in the industry is becoming increasingly popular as businesses strive to become more efficient and effective. As such, the Livinglab recently tested Workflow ai, a digital documentation platform, to see how it could help streamline processes and improve productivity.#workflowai #livinglab",
        Date: "2023-08-21 00:00:00",
        image:
            "https://images.pexels.com/photos/16978372/pexels-photo-16978372.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e35adafa46c648294c6d6a",
        time: "2023-08-21 12:38:49.998039+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph:
            "Overall, the Livinglab's workflow AI-driven digital documentation solution can help businesses and organizations optimize their digital documentation processes. The AI-driven technology can help to make digital documentation more efficient and cost-effective. Additionally, the AI-driven technology can be used to ensure that digital documents are secure and up-to-date. The Livinglab's workflow AI-driven digital documentation solution is an effective way to optimize digital documentation processes in the industry.#SocialMediaAutomation",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/7128991/pexels-photo-7128991.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e48f1d130773aa93e8c1c5",
        time: "2023-08-22 10:34:04.753091+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph:
            "Overall, the Livinglab's workflow AI-driven digital documentation solution can help businesses and organizations optimize their digital documentation processes. The AI-driven technology can help to make digital documentation more efficient and cost-effective. Additionally, the AI-driven technology can be used to ensure that digital documents are secure and up-to-date. The Livinglab's workflow AI-driven digital documentation solution is an effective way to optimize digital documentation processes in the industry.",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/6623836/pexels-photo-6623836.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e4b5ba34cb1f58400e3b85",
        time: "2023-08-22 13:18:47.444391+00:00",
    },
    {
        title: "The Livinglab was optimising the Efficient testing credits.",
        paragraph: [
            "",
            "",
            "As the world of technology continues to evolve, the need for efficient testing credits has become increasingly important. Testing credits are a type of resource that allow companies to efficiently test their products and services, ensuring that they are up to date and functioning properly. In order to ensure that these testing credits are used in the most effective way possible, the Livinglab has been optimising the efficient testing credits to maximise their potential.",
            "",
            "The Livinglab is a global research and development company that focuses on optimising the use of testing credits. It works with companies to help them identify and implement the most efficient testing credits for their products and services. By doing this, the Livinglab is able to cut down on the time and resources needed to test products and services, while also ensuring that they are of the highest quality.",
            "",
            "The Livinglab has developed a number of tools and techniques to help companies optimise their testing credits. This includes a range of software tools that can be used to analyse and track the use of testing credits, as well as a range of analytics tools that can be used to identify areas where testing credits can be used more efficiently.",
            "",
            "The Livinglab has also developed a number of strategies for using testing credits in the most efficient way possible. This includes the use of predictive analytics to identify areas where testing credits can be used more effectively, as well as the use of machine learning algorithms to better understand how testing credits are used.",
            "",
            "In addition to this, the Livinglab has also developed a range of services that can be used to help companies optimise their testing credits. This includes a range of consulting services that can help companies to identify areas where testing credits can be used more effectively, as well as a range of training and education services that can help companies to better understand how to use testing credits in the most efficient way possible.",
            "",
            "Overall, the Livinglab has been optimising the efficient testing credits in order to help companies to better understand and use them in the most effective way. This has allowed companies to save time and resources when testing their products and services, while also ensuring that they are of the highest quality. As the world of technology continues to evolve, the use of testing credits is becoming increasingly important, and the Livinglab is helping to ensure that they are used in the most efficient way possible.",
        ],
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/3862638/pexels-photo-3862638.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e4c7453ef2fde5ba0409c9",
        time: "2023-08-22 14:33:39.012159+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph: "",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/295826/pexels-photo-295826.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e4c97c34cb1f58400e3bbe",
        time: "2023-08-22 14:43:08.364315+00:00",
    },
    {
        title:
            "The Livinglab was testing Social Media Automation digital documentation.",
        paragraph: "#socialmediautomation #aiwriter",
        Date: "2023-08-22 00:00:00",
        image:
            "https://images.pexels.com/photos/205316/pexels-photo-205316.png?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e4e35717f621910f3fe17c",
        time: "2023-08-22 16:33:27.489546+00:00",
    },
    {
        title:
            "Social Media Automation digital documentation was tested by the Livinglab.",
        paragraph: [],
        Date: "2023-08-23 00:00:00",
        image:
            "https://images.pexels.com/photos/6954220/pexels-photo-6954220.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e5bdc97d5a254f84e0bea2",
        time: "2023-08-23 08:05:27.850114+00:00",
    },
    {
        title:
            "Social Media Automation digital documentation was tested by the Livinglab.",
        paragraph: [],
        Date: "2023-08-23 00:00:00",
        image:
            "https://images.pexels.com/photos/5678243/pexels-photo-5678243.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e5c2f93bb765c7bce59b61",
        time: "2023-08-23 08:27:36.349958+00:00",
    },
    {
        title: "Workflow ai digital documentation was optimised by the Livinglab.",
        paragraph: [
            "",
            "",
            "The use of digital documentation in the workplace is becoming increasingly important, and the Livinglab has developed a workflow AI system to make it easier for businesses to optimise their workflow. By streamlining the process of creating, managing, and sharing digital documents, the Livinglab’s workflow AI system can save businesses time and money, while also improving the accuracy and efficiency of their operations.",
            "",
            "The Livinglab’s workflow AI system works by automating the process of creating, managing, and sharing digital documents. By using natural language processing, the system is able to understand the context of the document and the associated tasks, allowing it to suggest the best course of action for each step in the workflow. This helps to reduce the amount of time spent on manual tasks, and ensures that the workflow runs smoothly.",
            "",
            "The Livinglab’s workflow AI system also makes it easier for businesses to track the progress of their documents and tasks. By using analytics and machine learning, the system can monitor the progress of documents and tasks, and provide feedback on how they can be improved in the future. This helps to ensure that documents and tasks are completed quickly and accurately, and that the entire workflow is running as efficiently as possible.",
            "",
            "The Livinglab’s workflow AI system is already being used by businesses in a variety of industries, from healthcare to finance. By streamlining the process of creating, managing, and sharing digital documents, the system can help businesses save time and money, while also improving the accuracy and efficiency of their operations. As more businesses begin to embrace digital documentation, the Livinglab’s workflow AI system will become even more important.",
        ],
        Date: "2023-08-23 00:00:00",
        image:
            "https://images.pexels.com/photos/18069857/pexels-photo-18069857.png?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e5cd666c3b5f96ec6148fc",
        time: "2023-08-23 09:12:05.440111+00:00",
    },
    {
        title: "Efficient gaming was run by the Storytelling.",
        paragraph: [
            "The gaming industry has seen a surge in the use of storytelling as a way to make gaming more efficient and enjoyable. Storytelling has become an integral part of the gaming experience, as it allows players to become immersed in the game, and to experience a more engaging and interactive gaming experience.",
            "Storytelling in gaming can be used to create a more compelling and immersive experience for the player. This can be done by creating a storyline that draws the player into the game and encourages them to explore the environment. The storyline can also be used to introduce new characters, items, and events that add to the game's complexity. By using storytelling, developers can create a narrative that keeps players engaged and interested in the game.",
            "Storytelling can also be used to enhance the gaming experience. Developers can use storytelling to make the game more challenging and engaging. This can be done by introducing puzzles or other challenges that require the player to think critically and use their problem-solving skills. Storytelling can also be used to create a more realistic gaming experience, as developers can use storytelling to create a believable world and characters.",
            "Finally, storytelling can be used to create a more efficient gaming experience. By using storytelling, developers can create a game that is easy to understand and navigate. This can help players quickly learn the game mechanics and become more comfortable with the game. Additionally, storytelling can be used to create a more efficient gaming experience by introducing new elements that can help players progress through the game in a more efficient manner.",
            "Overall, storytelling has become an important tool in the gaming industry. By using storytelling, developers can create a more engaging and immersive gaming experience for the player. Additionally, storytelling can be used to make the game more efficient and enjoyable. As such, storytelling is an important part of the gaming industry, and developers should consider using it to create a more efficient and enjoyable gaming experience.",
        ],
        Date: "2023-08-25 00:00:00",
        image:
            "https://images.pexels.com/photos/163239/baseball-player-running-sport-163239.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: "https://openai.com",
        PK: "64e857409c6255a2b064cca0",
        time: "2023-08-25 07:24:48.091558+00:00",
    },
    {
        title:
            "Social Media Automation digital documentation was tested by the Livinglab.",
        paragraph: "",
        Date: "2023-08-25 00:00:00",
        image:
            "https://images.pexels.com/photos/2818118/pexels-photo-2818118.jpeg?auto=compress&cs=tinysrgb&h=350",
        source: " https://openai.com",
        PK: "64e86697d9b86155316d5551",
        time: "2023-08-25 08:30:15.095643+00:00",
    },
    {
        title: "The Livinglab had tested workflow ai digital documentation.",
        paragraph:
            "The Livinglab has recently tested workflow AI digital documentation, which is a revolutionary tool for the industry.  This AI-based system can help streamline processes and make them more efficient, saving businesses time and money.  With this technology, companies can create automated workflows that can be used to manage tasks and documents, which can help reduce manual labor and increase productivity.  Additionally, the AI-based system can be used to track and monitor data, making it easier to analyze and report on the performance of a business.  This technology can be used in a variety of industries, from healthcare to finance, to help businesses make better decisions and increase their efficiency. ",
        Date: "2023-08-28 00:00:00",
        image: null,
        source: "https://openai.com",
        PK: "64ec909b87c0ad916a92bab5",
        time: "2023-08-28 12:17:55.933769+00:00",
    },
    {
        title: "Workflow ai digital documentation was tested by the Livinglab.",
        paragraph:
            "Workflow ai digital documentation is quickly becoming the go-to tool for streamlining document management in many industries.  The Livinglab recently conducted a test to see how well this technology works in a real-world setting.  The results were positive, showing that Workflow ai digital documentation is an effective way to reduce paperwork and improve efficiency.  This technology is especially useful for industries that require a lot of paperwork, such as healthcare, finance, and legal.  #test #Bogotá #Bradford #Brisbane",
        Date: "2023-10-09 00:00:00",
        image:
            "http://dowellfileuploader.uxlivinglab.online/camera_component_images/pexels-photo-18069696.png",
        source: null,
        PK: "6523ea3463cebca4ac078167",
        time: "2023-10-09 11:55:31.527907+00:00",
    },
];

const UnscheduledPage = () => {
    return (
        <div className='px-20'>
            <h3 className='text-[#495057] font-bold'>
                Total posts count: {dummyData.length}
            </h3>
            <ul className='space-y-10 '>
                {dummyData.map((item) => (
                    <li
                        id={item.PK}
                        key={item.PK}
                        className='flex justify-between gap-x-14'
                    >
                        <div className='flex flex-col w-9/12 gap-y-7 '>
                            <span className='text-base text-[#0000007c]'>{item.source}</span>
                            <h3 className='text-2xl font-bold text-customTextBlue'>
                                {item.title}
                            </h3>
                            <p className='text-[#333]'>{item.paragraph}</p>

                            <div className='self-end space-x-8'>
                                <Modal article={item} title='post'>
                                    <Dialog.Close asChild>
                                        <button
                                            className='text-violet11 hover:bg-violet4 focus:shadow-violet7 absolute top-[10px] right-[10px] inline-flex h-[25px] w-[25px] appearance-none items-center justify-center rounded-full focus:shadow-[0_0_0_2px] focus:outline-none'
                                            aria-label='Close'
                                        >
                                            <Cross2Icon/>
                                        </button>
                                    </Dialog.Close>
                                    <Dialog.Title className=' text-center text-[#1b3476] m-0 text-3xl font-semibold'>
                                        Where do you want to post?
                                    </Dialog.Title>
                                    <SocialComponentForPost article={item}/>
                                </Modal>
                                <Modal article={item} title='schedule'>
                                    <Dialog.Close asChild>
                                        <button
                                            className='text-violet11 hover:bg-violet4 focus:shadow-violet7 absolute top-[10px] right-[10px] inline-flex h-[25px] w-[25px] appearance-none items-center justify-center rounded-full focus:shadow-[0_0_0_2px] focus:outline-none'
                                            aria-label='Close'
                                        >
                                            <Cross2Icon/>
                                        </button>
                                    </Dialog.Close>
                                    <Dialog.Title className=' text-center text-[#1b3476] m-0 text-3xl font-semibold'>
                                        Where do you want to post?
                                    </Dialog.Title>
                                    <SocialComponentForSchedule article={item}/>
                                </Modal>
                            </div>
                        </div>
                        <img
                            className='w-40 h-40 mt-20 rounded-lg'
                            src={item.image}
                            alt='image'
                        />
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default UnscheduledPage;
