# Generated by Django 3.2.7 on 2022-12-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0004_auto_20220104_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='stepFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('paragraph', models.TextField(max_length=2000)),
                ('source', models.TextField(max_length=2000, null=True)),
                ('qcategorization', models.CharField(max_length=130)),
                ('targeted_for', models.CharField(max_length=130)),
                ('desgined_for', models.CharField(max_length=130)),
                ('targeted_category', models.CharField(max_length=130)),
                ('image', models.ImageField(upload_to='article_images/')),
            ],
        ),
    ]
