# Generated by Django 3.2.7 on 2022-12-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step2', '0005_stepfour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepfour',
            old_name='desgined_for',
            new_name='designed_for',
        ),
        migrations.RenameField(
            model_name='stepfour',
            old_name='qcategorization',
            new_name='qualitative_categorization',
        ),
    ]
