from django.urls import path

from . import views

app_name = 'generate_article'

urlpatterns = [
    # path('', views.under_maintenance, name='home'),
    # path('', views.home, name='home'),
    path('',views.dowell_login,name="dowelllogin"),
    path('main', views.main, name='main-view'),
    path('scheduled/', views.scheduled, name='scheduled-posts'),
    path('scheduled_json/', views.scheduled_json, name='scheduled-jsonposts'),
    path('schedule/', views.unscheduled, name='unscheduled-posts'),
    path('jsonpost/', views.unscheduled_json, name='unscheduled-jsonpost'),
    path('scheduler/', views.post_scheduler, name='post-scheduler'),
    path('posts_list/', views.post_list, name='article-list'),
    path('article_list/articles/', views.list_article_view, name='article-list-articles'),
    path('article_list/<str:filter>/', views.filtered_list_article, name='filtered-article-list'),
    path('post-detail/', views.post_detail, name='post-detail'),
    path('article-detail/', views.article_detail, name='article-detail'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('reset/password/', views.reset_password, name='reset-password'),
    path('confirm/reset/password/', views.confirm_reset_password, name='confirm-reset-password'),
    path('forget_password/', views.forget_password, name='forget_password'),
    path('user/approval/', views.user_approval, name='user-approval'),
    path('user/approval/form/', views.user_approval_form, name='user-approval-form'),
    path('user/approval/form_update/', views.user_approval_form_update, name='user-approval-update'),
    path('social_media_channels/', views.social_media_channels, name='social_media_channels'),
    path('link/linkusers/', views.aryshare_profile, name='aryshare'),
    path('link_social_media/', views.link_media_channels, name='link_social_media'),
    path('link/facebook/', views.facebook, name='facebook'),
    path('link/facebook/form/', views.facebook_form, name='facebook-form'),
    path('link/instagram/', views.insta, name='instagram'),
    path('link/instagram/form/', views.insta_form, name='instagram-form'),
    path('link/twitter/', views.twitter, name='twitter'),
    path('link/twitter/form/', views.twitter_form, name='twitter-form'),
    path('link/linkedin/', views.linkedin, name='linkedin'),
    path('link/linkedin/form/', views.linkedin_form, name='linkedin-form'),
    path('link/youtube/', views.youtube, name='youtube'),
    path('link/youtube/form/', views.youtube_form, name='youtube-form'),
    path('link/pinterest/', views.Pinterest, name='pinterest'),
    path('link/pinterest/form/', views.pinterest_form, name='pinterest-form'),
    path('client/profile/', views.client_profile, name='client-profile'),
    path('client/profile/form/', views.client_profile_form, name='client-profile-form'),
    path('client/', views.client, name='client'),
    path('user/team/', views.user_team, name='user-team'),
    path('user/usage/', views.user_usage, name='user-usage'),
    path('user/plan/', views.user_plan, name='user-plan'),
    path('comments/', views.comments, name='comments'),
    path('generate/comments/', views.generate_comments, name='generate-comments'),
    path('selected/comments/', views.selected_comments, name='selected-comment'),
    path('emoji/comments/', views.comments_emojis, name='comment-emoji'),
    path('topics/', views.topics, name='topics'),
    path('signup/', views.register, name='register'),
    path('article/generate/', views.index, name='index-view'),
    path('article/automate/', views.generate_article_automatically, name='automatic-view'),
    path('article/AI/', views.generate_article, name='submit-title'),
    path('article/Wiki/', views.generate_article_wiki, name='submit-title-wiki'),
    path('write/article/', views.write_yourself, name='write-yourself'),
    path('verify/article/', views.verify_article, name='verify-article'),
    path('user/info/', views.User_Info_ListView, name='user-info'),
    path('user/detail/<str:id>/', views.User_DetailView, name='user-detail'),
    path('address/', views.address, name='address'),
    path('recent/', views.most_recent, name='recent-post'),
    path('save_post/', views.Save_Post, name='save-post'),
    path('recent_json/', views.most_recent_json, name='recent_json'),
    path('media_post/', views.Media_Post, name='media-post'),
    path('media_schedule/', views.Media_schedule, name='media-schedule'),
    path('proxy-api/', views.frontend_api_request, name='proxy-api'),
    path('exit/', views.exit_view, name='exit'),
    path('target-cities/', views.targeted_cities, name='target_cities'),
    path('saved-target-cities/', views.save_targeted_cities,
         name='save_target_cities'),
    path('update-saved-target-cities/', views.update_saved_targeted_cities,
         name='update_saved_target_cities'),
    path('hash-tags-and-mentions/', views.hash_mention, name='save_hash_mention'),
    path('update-hash-tags-and-mensions/', views.update_hash_mention, name='update_hash_mention'),
    path('linked-account/', views.linked_account_json, name='linked-account'),
    path('logout',views.Logout,name="logout"),
    path('social-media/approve/', views.admin_approve_social_media, name='admin_approve_social_media'),
    # path('list/article',views.list_article, name='list-article'),
    # path('saved/',views.save_article,name='save-article'),
]
